In [16]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

# Loading Data
dataset = load_dataset(
    'lukebarousse/data_jobs',
    split='train'
)

# Convert to Pandas
df = dataset.to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

print("Data loaded successfully!")
print(df.shape)

Data loaded successfully!
(785741, 17)

In [17]:
df['salary_year_avg']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
785736   NaN
785737   NaN
785738   NaN
785739   NaN
785740   NaN
Name: salary_year_avg, Length: 785741, dtype: float64

In [18]:
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [19]:
def projected_salary(salary):
    return salary * 1.03

df['salary_year_avg'].apply(projected_salary)

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
785736   NaN
785737   NaN
785738   NaN
785739   NaN
785740   NaN
Name: salary_year_avg, Length: 785741, dtype: float64

In [20]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()

def projected_salary(salary):
    return salary * 1.03

df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary) 

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [21]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda salary: salary * 1.03)

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [22]:
df['job_skills'][5]

"['python', 'sql', 'gcp']"

In [23]:
import ast

In [24]:
type(ast.literal_eval(df['job_skills'][5]))

list

In [25]:
def clean_list(skill_list):
    if pd.notna(skill_list):
          return ast.literal_eval(skill_list)

df['job_skills'] = df['job_skills'].apply(clean_list)

In [29]:
df['job_skills'][5]

['python', 'sql', 'gcp']

In [ ]:
df['job_skills'] = df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else skill_list)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [31]:
df['job_skills'] = df['job_skills'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

In [32]:
df['job_skills'][5]

['python', 'sql', 'gcp']

In [38]:
df_salary.head(50)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,salary_year_inflated
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.00000,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd...",NaN
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.00000,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac...",NaN
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.00000,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}",NaN
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.00000,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr...",NaN
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.00000,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro...",NaN
116,Data Scientist,Data Scientist,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-10-04 13:04:23,False,False,United States,year,114000.00000,NaN,4 Corner Resources,"['r', 'python', 'sql', 't-sql', 'hadoop', 'spa...","{'analyst_tools': ['tableau'], 'libraries': ['...",NaN
146,Data Engineer,Data Engineer Graduate (Real Time Communicatio...,"Seattle, WA",via LinkedIn,Full-time,False,"California, United States",2023-10-21 13:06:16,False,True,United States,year,129500.00000,NaN,ByteDance,"['golang', 'scala', 'python', 'java', 'hadoop'...","{'libraries': ['hadoop', 'spark'], 'programmin...",NaN
180,Data Analyst,Data Analyst III,"Dos Palos, CA",via My ArkLaMiss Jobs,Full-time,False,"California, United States",2023-02-27 13:00:39,False,True,United States,year,90250.00000,NaN,California Health & Wellness,"['excel', 'powerpoint']","{'analyst_tools': ['excel', 'powerpoint']}",NaN
212,Data Scientist,NATOIS-0008 Data Scientist (NS) - TUE 13 Jun,"Brussels, Belgium",via Ai-Jobs.net,Full-time,False,Belgium,2023-06-05 13:56:28,False,False,Belgium,year,157500.00000,NaN,"EMW, Inc.","['c', 'r', 'sql', 'python', 'aws', 'azure', 'h...","{'analyst_tools': ['tableau'], 'cloud': ['aws'...",NaN
257,Data Scientist,Senior Bioinformatics Research Scientist- Data...,"Brighton, TN",via Work RN,Full-time,False,Georgia,2023-11-20 13:40:09,False,False,United States,year,103128.00000,NaN,St. Jude Children's Research Hospital,"['r', 'electron']","{'libraries': ['electron'], 'programming': ['r']}",NaN
307,Data Engineer,Data Engineer,"Austin, TX",via LinkedIn,Full-time,False,"New York, United States",2023-10-03 13:05:31,False,False,United States,year,185000.00000,NaN,hackajob,"['nosql', 'sql']","{'programming': ['nosql', 'sql']}",NaN
339,Data Engineer,Global Market Leading Energy Firm - Staff Data...,United States,via LinkedIn,Full-time,False,"California, United States",2023-09-22 13:07:57,False,False,United States,year,195000.00000,NaN,Xcede,NaN,NaN,NaN
380,Data Engineer,Snaplogic Data Engineer,"Durham, NC",via LinkedIn,Full-time,False,"Illinois, United States",2023-08-16 13:26:21,True,False,United States,year,97500.00000,NaN,KTek Resourcing,"['sql', 'python']","{'programming': ['sql', 'python']}",NaN
388,Data Engineer,Data Engineer,"New Ulm, MN",via KSNT Jobs,Full-time,False,"Florida, United States",2023-08-20 13:32:05,False,False,United States,year,89000.00000,NaN,Ledgent Technology,"['sql', 'python', 'power bi']","{'analyst_tools': ['power bi'], 'programming':...",NaN
410,Data Analyst,IT Business Lead Data Analyst - VP - Hybrid,"Atlantic Beach, FL",via ComputerJobs.com,Full-time,False,Georgia,2023-01-10 13:59:02,False,False,United States,year,133285.00000,NaN,Citi,"['sql', 'word', 'excel', 'visio', 'powerpoint'...","{'analyst_tools': ['word', 'excel', 'visio', '...",NaN
450,Data Scientist,Data Defense Developer - USDS,"Mountain View, CA",via LinkedIn,Full-time,False,"New York, United States",2023-12-02 13:19:59,False,True,United States,year,157500.00000,NaN,TikTok,"['go', 'python', 'java', 'mongo', 'redis', 'aw...","{'cloud': ['aws'], 'databases': ['redis'], 'li...",NaN
495,Senior Data Engineer,Senior Software Engineer (Data),"San Francisco, CA",via LinkedIn,Full-time,False,"Illinois, United States",2023-06-20 13:07:37,False,True,United States,year,168500.00000,NaN,hackajob,"['scala', 'gcp', 'azure', 'spark', 'kafka', 'h...","{'cloud': ['gcp', 'azure'], 'libraries': ['spa...",176925.0
520,Business Analyst,Power BI Analyst,"San Pedro Sula, Honduras",via Ai-Jobs.net,Full-time,False,Honduras,2023-07-24 14:05:29,True,False,Honduras,year,63000.00000,NaN,Charger Logistics Inc,['power bi'],{'analyst_tools': ['power bi']},NaN
545,Data Engineer,ERP Data Engineer,"Lansing, MI",via LinkedIn,Full-time,False,Sudan,2023-01-04 13:58:44,False,False,Sudan,year,80000.00000,NaN,Venteon,"['sql', 'sap']","{'analyst_tools': ['sap'], 'programming': ['sq...",NaN
571,Data Engineer,Data Engineer ETL lnformatica API SQL Engineer...,Anywhere,via Robert Half,Full-time,True,"California, United States",2023-07-20 13:07:40,True,False,United States,year,110000.00000,NaN,Robert Half,"['sql', 'java', 'python', 'azure', 'aws', 'sno...","{'cloud': ['azure', 'aws', 'snowflake'], 'prog...",NaN
573,Senior Data Engineer,Senior Python Data Engineer,"Wilmington, DE",via Indeed,Full-time,False,Sudan,2023-09-16 13:13:50,False,False,Sudan,year,160000.00000,NaN,Crackajack Solutions,"['python', 'sql', 'java', 'aws', 'databricks',...","{'cloud': ['aws', 'databricks', 'redshift'], '...",168000.0
645,Business Analyst,Lead BI Analyst,"Irvine, CA",via LinkedIn,Full-time,False,"California, United States",2023-08-11 13:01:18,False,False,United States,year,125000.00000,NaN,KORE1,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ...",NaN
654,Data Engineer,Lead Data Engineer (DataStage) (Need only loca...,"Cincinnati, OH",via Dice.com,Contractor,False,Sudan,2023-09-22 13:38:56,True,False,Sudan,year,70000.00000,NaN,Strategic Systems Inc,NaN,NaN,NaN
657,Senior Data Engineer,Senior Data Engineer | Series D Video Analytic...,"Culver City, CA",via LinkedIn,Full-time,False,Georgia,2023-10-09 14:07:46,False,True,United States,year,165000.00000,NaN,Coda Search│Staffing,"['python', 'scala', 'sql', 'aws', 'redshift', ...","{'cloud': ['aws', 'redshift'], 'libraries': ['...",173250.0
679,Software Engineer,"Tech Lead Software Engineer, TikTok Data Access","San Jose, CA",via LinkedIn,Full-time,False,"Illinois, United States",2023-12-31 13:03:14,False,True,United States,year,317000.00000,NaN,TikTok,"['java', 'go', 'c++', 'python', 'mongodb', 'mo...","{'databases': ['mongodb', 'mysql', 'redis'], '...",NaN
704,Data Engineer,"Data Engineer, Azure",United States,via LinkedIn,Full-time and Contractor,False,"Illinois, United States",2023-10-11 13:07:54,True,False,United States,year,100000.00000,NaN,Technical Source,"['sql', 'python', 'azure', 'databricks']","{'cloud': ['azure', 'databricks'], 'programmin...",NaN
719,Data Engineer,Azure Data Engineer,"Scottsdale, AZ",via Indeed,Full-time,False,"California, United States",2023-05-15 13:22:59,True,False,United States,year,111228.15625,NaN,TEKletics,"['sql', 'python', 'azure']","{'cloud': ['azure'], 'programming': ['sql', 'p...",NaN
726,Senior Data Engineer,Senior Data Engineer (Hybrid),"Washington, DC",via Linux Careers,Full-time,False,"California, United States",2023-05-02 13:09:09,False,True,United States,year,173500.00000,NaN,Capital One,"['java', 'scala', 'python', 'nosql', 'sql', 's...","{'cloud': ['redshift', 'snowflake', 'aws', 'az...",182175.0
733,Senior Data Engineer,Senior Data Engineer,"Oakland, CA",via LinkedIn,Full-time,False,Sudan,2023-07-06 13:41:35,False,False,Sudan,year,160000.00000,NaN,X4 Life Sciences,"['python', 'sql', 'postgresql', 'sql server', ...","{'cloud': ['aws', 'snowflake'], 'databases': [...",168000.0
762,Data Engineer,"Data Engineer, Big Data Privacy and Security","San Jose, CA",via LinkedIn,Full-time,False,Sudan,2023-06-18 13:38:44,False,True,Sudan,year,171000.00000,NaN,TikTok,"['spark', 'kafka']","{'libraries': ['spark', 'kafka']}",NaN
773,Data Engineer,Principal Data Engineer,Anywhere,via Indeed,Full-time,True,"Texas, United States",2023-05-17 13:22:20,True,False,United States,year,180000.00000,NaN,CyberCoders,"['sql', 'python', 'aws', 'snowflake', 'spark',...","{'analyst_tools': ['tableau', 'microstrategy']...",NaN
813,Data Engineer,Azure Data Engineer,United States,via Dice,Full-time,False,"Florida, United States",2023-02-28 13:14:02,False,True,United States,year,157500.00000,NaN,Jobot,"['t-sql', 'c#', 'python', 'sql', 'azure', 'git...","{'cloud': ['azure'], 'other': ['github'], 'pro...",NaN
923,Data Engineer,AWS Data Engineer,Anywhere,via LinkedIn,Full-time,True,"California, United States",2023-08-09 13:05:40,False,True,United States,year,135000.00000,NaN,Effectual Inc.,"['python', 'sql', 'java', 'scala', 'nosql', 'a...","{'cloud': ['aws', 'azure', 'redshift', 'bigque...",NaN
982,Senior Data Analyst,Senior Data Analyst,"Los Angeles, CA",via Dice,Full-time,False,"California, United States",2023-02-03 13:01:29,False,False,United States,year,85000.00000,NaN,Jobot,"['sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sa...",89250.0
988,Data Analyst,DATA ANALYST (ONSITE),"Springfield, MA",via Indeed,Full-time,False,"New York, United States",2023-11-21 13:00:13,False,False,United States,year,62623.00000,NaN,Springfield Public Schools,"['sql', 'excel', 'tableau']","{'analyst_tools': ['excel', 'tableau'], 'progr...",NaN
990,Senior Data Analyst,Senior Data Analyst,"Fort Lauderdale, FL",via Ladders,Full-time,False,"Florida, United States",2023-01-02 13:01:55,False,True,United States,year,90000.00000,NaN,The Farmer's Dog,"['excel', 'sheets']","{'analyst_tools': ['excel', 'sheets']}",94500.0
993,Data Engineer,Data Engineer Level 2,"Blue Ash, OH",via Dice,Full-time,False,Sudan,2023-07-11 14:10:29,True,False,Sudan,year,125000.00000,NaN,Symantrix Inc,"['sql', 't-sql', 'azure', 'selenium', 'ansible...","{'cloud': ['azure'], 'libraries': ['selenium']...",NaN
1011,Senior Data Engineer,Senior Data Engineer,"Southfield, MI",via Ladders,Full-time,False,"New York, United States",2023-08-09 13:04:52,False,True,United States,year,90000.00000,NaN,Sun Communities,"['sql', 'python', 'c#', 'java', 'javascript', ...","{'cloud': ['azure', 'databricks'], 'programmin...",94500.0
1042,Machine Learning Engineer,Head of AML Operations (m/f/d),"Ballerup, Denmark",via Ai-Jobs.net,Full-time,False,Denmark,2023-06-14 13:25:40,False,False,Denmark,year,105300.00000,NaN,Nets,NaN,NaN,NaN
1106,Data Engineer,Data Engineer,"Dallas, TX",via LinkedIn,Full-time,False,"Florida, United States",2023-04-10 13:08:31,False,True,United States,year,137500.00000,NaN,WEX,"['go', 'python', 'pyspark', 'spark']","{'libraries': ['pyspark', 'spark'], 'programmi...",NaN
1107,Data Scientist,"Data Scientist, Customer AI Engineering","London, UK",via Ai-Jobs.net,Full-time,False,United Kingdom,2023-06-20 13:12:50,False,False,United Kingdom,year,157500.00000,NaN,Tractable,"['python', 'numpy', 'pandas', 'scikit-learn']","{'libraries': ['numpy', 'pandas', 'scikit-lear...",NaN
1148,Senior Data Engineer,Senior Data Engineer,"San Mateo, CA",via LinkedIn,Full-time,False,Sudan,2023-05-17 14:10:56,False,False,Sudan,year,155000.00000,NaN,Intelletec,"['python', 'aws']","{'cloud': ['aws'], 'programming': ['python']}",162750.0
1164,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-10-09 13:30:25,False,True,United States,year,190000.00000,NaN,FirstParty,"['sql', 'python', 'r', 'aws', 'airflow', 'matp...","{'analyst_tools': ['tableau', 'looker'], 'clou...",NaN
1209,Machine Learning Engineer,Computer Vision Developer (R&D),"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-02-18 13:12:30,False,False,India,year,79200.00000,NaN,Bosch Group,"['python', 'opencv', 'tensorflow', 'pytorch', ...","{'libraries': ['opencv', 'tensorflow', 'pytorc...",NaN
1238,Senior Data Engineer,Senior Software (Data) Engineer - Advanced Rob...,Anywhere,via LinkedIn,Full-time,True,Georgia,2023-03-14 13:48:49,False,False,United States,year,190000.00000,NaN,TEEMA,"['python', 'kafka', 'django']","{'libraries': ['kafka'], 'programming': ['pyth...",199500.0
1257,Data Scientist,Data Scientist,"Minneapolis, MN",via Adzuna,Full-time,False,"Illinois, United States",2023-02-21 13:25:40,False,True,United States,year,70700.00000,NaN,Target,"['java', 'scala', 'python', 'r', 'kotlin', 'sq...","{'libraries': ['spark'], 'programming': ['java...",NaN
1261,Senior Data Engineer,"Senior Data Engineer - SQL, Snowflake",Anywhere,via Indeed,Full-time,True,"Florida, United States",2023-05-12 13:27:56,True,True,United States,year,180000.00000,NaN,CyberCoders,"['sql', 'python', 'snowflake', 'redshift', 'aw...","{'cloud': ['snowflake', 'redshift', 'aws'], 'l...",189000.0
1280,Software Engineer,Senior Software Engineer - Live Streaming Infr...,"Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-09 13:04:23,False,True,United States,year,233500.00000,NaN,TikTok,"['c', 'c++', 'java', 'python', 'go', 'hadoop',...","{'libraries': ['hadoop', 'spark', 'kafka'], 'p...",NaN
1284,Data Engineer,Sr. Data Engineer,"Indianapolis, IN",via Indeed,Full-time,False,"Illinois, United States",2023-06-20 13:07:12,True,False,United States,year,102500.00000,NaN,Insight Global,"['sql', 'powershell', 'azure', 'snowflake', 's...","{'cloud': ['azure', 'snowflake'], 'libraries':...",NaN
1313,Data Engineer,Staff Data Engineer,"Tel Aviv-Yafo, Israel",via Ai-Jobs.net,Full-time,False,Israel,2023-09-01 13:54:54,True,False,Israel,year,79200.00000,NaN,DoubleVerify,"['python', 'scala', 'sql', 'java', 'gcp', 'dat...","{'cloud': ['gcp', 'databricks', 'bigquery'], '...",NaN

In [45]:
def projected_salary(row):
    if "Senior" in row['job_title_short']:
        return 1.05 * row['salary_year_avg']
    else:
        return 1.03 * row['salary_year_avg']

df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis=1)

df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]

In [46]:
df['salary_year_inflated'] = df.apply(lambda row: 1.05 * row['salary_year_avg'] if 'Senior' in row['job_title_short'] else 1.03 * row['salary_year_avg'], axis=1)

df[pd.notna(df['salary_year_avg'])][['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]