In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

# Loading Data
dataset = load_dataset(
    'lukebarousse/data_jobs',
    split='train'
)

# Convert to Pandas
df = dataset.to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

print("Data loaded successfully!")
print(df.shape)

ModuleNotFoundError: No module named 'datasets'

In [2]:
%pip install datasets

Collecting datasets
  Downloading datasets-5.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: filelock in c:\Users\LENOVO\anaconda3\Lib\site-packages (from datasets) (3.29.4)
Requirement already satisfied: numpy>=1.17 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from datasets) (2.4.6)
Requirement already satisfied: pyarrow>=21.0.0 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in c:\Users\LENOVO\anaconda3\Lib\site-packages (from datasets) (3.0.3)
Requirement already satisfied: requests>=2.32.2 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from datasets) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from datasets) (4.68.2)
Collecting xxhash (from datasets)
  Downloading xxhash-4.0.1-cp314-cp314-win_amd64.whl.metadata (18 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py314-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2026.4.0)
Collecting huggingface-hub<2.0,>=0.25.0 (from datasets)
  Downloading huggingface_hub-1.30.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: packaging in c:\Users\LENOVO\anaconda3\Lib\site-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in c:\Users\LENOVO\anaconda3\Lib\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in c:\Users\LENOVO\anaconda3\Lib\site-packages (from httpx<1.0.0->datasets) (2026.6.17)
Requirement already satisfied: httpcore==1.* in c:\Users\LENOVO\anaconda3\Lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\Users\LENOVO\anaconda3\Lib\site-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Collecting hf-xet<2.0.0,>=1.5.2 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: colorama in c:\Users\LENOVO\anaconda3\Lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\LENOVO\anaconda3\Lib\site-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\LENOVO\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-5.0.1-py3-none-any.whl (559 kB)
   ---------------------------------------- 0.0/559.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/559.1 kB ? eta -:--:--
   ---------------------------------------- 559.1/559.1 kB 1.7 MB/s  0:00:00
Downloading huggingface_hub-1.30.0-py3-none-any.whl (796 kB)
   ---------------------------------------- 0.0/796.8 kB ? eta -:--:--
   ------------- -------------------------- 262.1/796.8 kB ? eta -:--:--
   ---------------------------------------- 796.8/796.8 kB 2.0 MB/s  0:00:00
Downloading click-8.5.0-py3-none-any.whl (125 kB)
Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 2.1 MB/s eta 0:00:02
   ------- -------------------------------- 0.8/4.0 MB 2.1 MB/s eta 0:00:02
   --------------- ------------------------ 1.6/4.0 MB 2.2 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.0 MB 2.3 MB/s eta 0:00:01
   -------------------- ------------------- 2.1/4.0 MB 2.3 MB/s eta 0:00:01
   ---------------------------- ----------- 2.9/4.0 MB 2.2 MB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 2.1 MB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 2.1 MB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 1.8 MB/s  0:00:02
Downloading multiprocess-0.70.19-py314-none-any.whl (160 kB)
Downloading xxhash-4.0.1-cp314-cp314-win_amd64.whl (37 kB)
Installing collected packages: xxhash, multiprocess, hf-xet, click, huggingface-hub, datasets

   ------ --------------------------------- 1/6 [multiprocess]
   ------ --------------------------------- 1/6 [multiprocess]
   ------ --------------------------------- 1/6 [multiprocess]
   ------------- -------------------------- 2/6 [hf-xet]
  Attempting uninstall: click
   ------------- -------------------------- 2/6 [hf-xet]
    Found existing installation: click 8.4.1
   ------------- -------------------------- 2/6 [hf-xet]
   -------------------- ------------------- 3/6 [click]
    Uninstalling click-8.4.1:
   -------------------- ------------------- 3/6 [click]
      Successfully uninstalled click-8.4.1
   -------------------- ------------------- 3/6 [click]
   -------------------- ------------------- 3/6 [click]
   -------------------- ------------------- 3/6 [click]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [huggingface-hub]
   --------------------------------- ------ 5/6 [datasets]
   --------------------------------- ------ 5/6 [datasets]
   --------------------------------- ------ 5/6 [datasets]
   --------------------------------- ------ 5/6 [datasets]
   --------------------------------- ------ 5/6 [datasets]
   --------------------------------- ------ 5/6 [datasets]
   --------------------------------- ------ 5/6 [datasets]
   --------------------------------- ------ 5/6 [datasets]
   --------------------------------- ------ 5/6 [datasets]
   --------------------------------- ------ 5/6 [datasets]
   --------------------------------- ------ 5/6 [datasets]
   --------------------------------- ------ 5/6 [datasets]
   --------------------------------- ------ 5/6 [datasets]
   ---------------------------------------- 6/6 [datasets]

Successfully installed click-8.5.0 datasets-5.0.1 hf-xet-1.6.0 huggingface-hub-1.30.0 multiprocess-0.70.19 xxhash-4.0.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

# Loading Data
dataset = load_dataset(
    'lukebarousse/data_jobs',
    split='train'
)

# Convert to Pandas
df = dataset.to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

print("Data loaded successfully!")
print(df.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Data loaded successfully!
(785741, 17)

In [4]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [5]:
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
686029,Data Analyst,Data Analytics,"Poznań, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-12-26 10:09:44,True,False,Poland,NaN,NaN,NaN,GSK,"['sql', 'azure', 'power bi']","{'analyst_tools': ['power bi'], 'cloud': ['azu..."
150520,Data Analyst,Credit Risk Data Analyst - Now Hiring,"Tampa, FL",via Snagajob,Full-time,False,"Florida, United States",2023-01-29 08:02:36,True,False,United States,NaN,NaN,NaN,Selby Jennings,"['sas', 'sas', 'sql', 'r', 'python']","{'analyst_tools': ['sas'], 'programming': ['sa..."
782292,Senior Data Engineer,Senior Data Engineer,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-09-28 06:05:37,True,False,United States,NaN,NaN,NaN,gWorks,"['sql', 't-sql', 'postgresql', 'sql server', '...","{'cloud': ['aws', 'aurora', 'azure'], 'databas..."
400371,Data Scientist,Data Scientist II,"Dallas, TX",via BeBee,Full-time,False,Sudan,2023-02-28 18:36:19,False,False,Sudan,NaN,NaN,NaN,Chewy,"['python', 'sql', 'r', 'sas', 'sas', 'scala', ...","{'analyst_tools': ['sas'], 'cloud': ['aws', 'r..."
779388,Software Engineer,Software Development Engineer,"Schiphol, Netherlands",via BeBee,Temp work,False,Netherlands,2023-09-30 05:19:50,False,False,Netherlands,NaN,NaN,NaN,KLM,['c++'],{'programming': ['c++']}

In [6]:
df.index.name = 'job_index'

In [7]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [8]:
df.index.dtype

dtype('int64')

In [9]:
df_usa = df[df['job_country'] == 'United States']

In [10]:
df_usa

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,NaN,NaN,NaN,JPMorgan Chase & Co.,NaN,NaN
785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,NaN,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,NaN,NaN,NaN,Axelon Services Corporation,NaN,NaN
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,NaN,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [12]:
df_usa.reset_index(inplace = True)
df_usa

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
2,5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
3,6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
4,9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206287,785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,NaN,NaN,NaN,JPMorgan Chase & Co.,NaN,NaN
206288,785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,NaN,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
206289,785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
206290,785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,NaN,NaN,NaN,Axelon Services Corporation,NaN,NaN
206291,785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,NaN,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [14]:
df_usa.set_index('job_index', inplace = True)

In [15]:
df_usa

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,NaN,NaN,NaN,JPMorgan Chase & Co.,NaN,NaN
785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,NaN,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,NaN,NaN,NaN,Axelon Services Corporation,NaN,NaN
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,NaN,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [16]:
median_pivot = df_usa.pivot_table(values='salary_year_avg',index='job_title_short',aggfunc=['median','min','max'])

In [17]:
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  90000.0         35000.0        387460.0
Cloud Engineer                   116100.0         42000.0        221844.0
Data Analyst                      90000.0         25000.0        375000.0
Data Engineer                    125000.0         23496.0        525000.0
Data Scientist                   130000.0         30000.0        960000.0
Machine Learning Engineer        150000.0         44408.5        315000.0
Senior Data Analyst              110000.0         35360.0        425000.0
Senior Data Engineer             150000.0         45000.0        375000.0
Senior Data Scientist            155000.0         55000.0        475000.0
Software Engineer                130000.0         48982.0        375000.0

In [20]:
median_pivot.sort_values(by=('median','salary_year_avg'),ascending = False)

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Senior Data Scientist            155000.0         55000.0        475000.0
Machine Learning Engineer        150000.0         44408.5        315000.0
Senior Data Engineer             150000.0         45000.0        375000.0
Data Scientist                   130000.0         30000.0        960000.0
Software Engineer                130000.0         48982.0        375000.0
Data Engineer                    125000.0         23496.0        525000.0
Cloud Engineer                   116100.0         42000.0        221844.0
Senior Data Analyst              110000.0         35360.0        425000.0
Business Analyst                  90000.0         35000.0        387460.0
Data Analyst                      90000.0         25000.0        375000.0

In [21]:
median_pivot.sort_index()

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  90000.0         35000.0        387460.0
Cloud Engineer                   116100.0         42000.0        221844.0
Data Analyst                      90000.0         25000.0        375000.0
Data Engineer                    125000.0         23496.0        525000.0
Data Scientist                   130000.0         30000.0        960000.0
Machine Learning Engineer        150000.0         44408.5        315000.0
Senior Data Analyst              110000.0         35360.0        425000.0
Senior Data Engineer             150000.0         45000.0        375000.0
Senior Data Scientist            155000.0         55000.0        475000.0
Software Engineer                130000.0         48982.0        375000.0